# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Preventanyl' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Preventanyl

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'SHSPhoneComponent'

  target 'PreventanylTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PreventanylUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
